"use client";
import Link from "next/link";
import { flexRender, getCoreRowModel, useReactTable, type ColumnDef } from "@tanstack/react-table";
import { MoreHorizontal } from "lucide-react";
import type { Employee } from "@/types/employee";
import { StatusBadge } from "@/components/ui/badge";
import { Dropdown, DropdownContent, DropdownItem, DropdownTrigger } from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
const columns:ColumnDef<Employee>[]=[{header:"Employee",cell:({row})=><div><Link className="font-semibold text-slate-950 hover:text-blue-600" href={`/employees/${row.original.id}`}>{row.original.firstName} {row.original.lastName}</Link><p className="text-xs text-slate-500">{row.original.employeeCode} · {row.original.user.email}</p></div>},{header:"Department",accessorFn:r=>r.department??"—"},{header:"Office",accessorFn:r=>r.office?.name??"Unassigned"},{header:"Schedule",accessorFn:r=>r.schedule?.name??"Unassigned"},{header:"Status",cell:({row})=><StatusBadge status={row.original.status}/>},{id:"actions",cell:({row})=><Dropdown><DropdownTrigger asChild><Button variant="ghost" size="sm" aria-label={`Actions for ${row.original.firstName}`}><MoreHorizontal className="size-4"/></Button></DropdownTrigger><DropdownContent align="end"><DropdownItem asChild><Link href={`/employees/${row.original.id}`}>View employee</Link></DropdownItem></DropdownContent></Dropdown>}];
export function EmployeeTable({data}:{data:Employee[]}){const table=useReactTable({data,columns,getCoreRowModel:getCoreRowModel()});return <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500">{table.getHeaderGroups().map(h=><tr key={h.id}>{h.headers.map(x=><th key={x.id} className="px-4 py-3 font-semibold">{flexRender(x.column.columnDef.header,x.getContext())}</th>)}</tr>)}</thead><tbody className="divide-y">{table.getRowModel().rows.map(r=><tr key={r.id} className="hover:bg-slate-50/70">{r.getVisibleCells().map(c=><td key={c.id} className="px-4 py-4 align-middle">{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table></div>}
