export type Office = { id:string; name:string; address?:string|null; isActive:boolean };
export type ScheduleDay = { weekday:number; checkInTime:string; checkOutTime:string };
export type Schedule = { id:string; name:string; checkInTime:string; checkOutTime:string; lateGraceMinutes:number; workingDays:number[]; days?:ScheduleDay[]; isActive:boolean };
export type Department = { id: string; name: string; isActive: boolean };
export type EvaluationTemplateOption = { id: string; name: string; jobTitleHint?: string | null; isDefault?: boolean };
export type EmployeeSupervisor = {
  id: string;
  firstName: string;
  middleName?: string | null;
  lastName: string;
  jobTitle?: string | null;
  userId: string;
};
export type Employee = {
  id: string;
  userId: string;
  employeeCode: string;
  firstName: string;
  middleName?: string | null;
  lastName: string;
  phone?: string | null;
  jobTitle?: string | null;
  departmentId?: string | null;
  evaluationTemplateId?: string | null;
  employmentStartDate: string;
  status: "ACTIVE" | "INACTIVE" | "TERMINATED";
  officeId?: string | null;
  scheduleId?: string | null;
  supervisorId?: string | null;
  supervisor?: EmployeeSupervisor | null;
  supervisorHasPortalAccess?: boolean;
  createdAt?: string;
  updatedAt?: string;
  user: { id: string; email: string; status: string; mustChangePassword: boolean; lastLoginAt?: string | null };
  office?: Office | null;
  schedule?: Schedule | null;
  department?: Department | null;
  evaluationTemplate?: EvaluationTemplateOption | null;
};
export type PageMeta = { page:number; pageSize:number; total:number; totalPages:number };
export type EmployeeList = { items:Employee[]; meta:PageMeta };
